services:
  frigate:
    container_name: fras-frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    shm_size: "128mb"
    devices:
      - /dev/dri:/dev/dri # Hardware Acceleration for UGREEN NAS Intel CPU
    environment:
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - CAMERA_IP=${CAMERA_IP}
      - CAMERA_USER=${CAMERA_USER}
      - CAMERA_PASSWORD=${CAMERA_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./configuration/frigate.yml:/config/config.yml:ro
      - ./frigate/storage:/media/frigate
    ports:
      - "5000:5000" # Web Interface
      - "8554:8554" # Multiplexing go2rtc
      - "8555:8555/tcp"
      - "8555:8555/udp"
    restart: unless-stopped
    networks:
      - fras-network

  double-take:
    container_name: fras-double-take
    image: jakowenko/double-take:latest
    restart: unless-stopped
    environment:
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - COMPREFACE_API_KEY=${COMPREFACE_API_KEY}
    volumes:
      - ./double-take/.storage:/double-take/.storage
      - ./configuration/double-take.yml:/double-take/config.yml:ro
    ports:
      - "3000:3000"
    depends_on:
      - frigate
      - compreface-front-end
    networks:
      - fras-network

  compreface-postgres-db:
    container_name: fras-compreface-postgres-db
    image: postgres:11.5
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-compreface}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-compreface}
      - POSTGRES_DB=${POSTGRES_DB:-compreface}
    volumes:
      - ./compreface/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - fras-network

  compreface-admin:
    container_name: fras-compreface-admin
    image: exadel/compreface-admin:latest
    restart: unless-stopped
    depends_on:
      - compreface-postgres-db
      - compreface-api
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-compreface}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-compreface}
      - POSTGRES_URL=jdbc:postgresql://compreface-postgres-db:5432/${POSTGRES_DB:-compreface}
      - SPRING_PROFILES_ACTIVE=dev
      - ENABLE_EMAIL_SERVER=false
    networks:
      - fras-network

  compreface-api:
    container_name: fras-compreface-api
    image: exadel/compreface-api:latest
    restart: unless-stopped
    depends_on:
      - compreface-postgres-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-compreface}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-compreface}
      - POSTGRES_URL=jdbc:postgresql://compreface-postgres-db:5432/${POSTGRES_DB:-compreface}
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - fras-network

  compreface-front-end:
    container_name: fras-compreface-front-end
    image: exadel/compreface-fe:latest
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - compreface-api
      - compreface-admin
    environment:
      - CLIENT_MAX_BODY_SIZE=10M
      - PROXY_READ_TIMEOUT=60000ms
      - PROXY_CONNECT_TIMEOUT=10000ms
    networks:
      - fras-network

  compreface-core:
    container_name: fras-compreface-core
    image: exadel/compreface-core:latest
    restart: unless-stopped
    environment:
      - ML_PORT=3000
    ports:
      - "3001:3000"
    networks:
      - fras-network

networks:
  fras-network:
    driver: bridge