name: Deploy to NAS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy Stack on Local NAS
    runs-on: self-hosted
    steps:
      - name: Pull Latest Changes and Recreate Containers
        run: |
          git config --global --add safe.directory /volume1/docker/face-recognition-alarm-system
          cd /volume1/docker/face-recognition-alarm-system
          git pull origin main
          docker compose up -d --remove-orphans